### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by cboto314** [mxrch/revealin#1]
Could you help me fix this error?

```
┌──(osint㉿osint)-[~/Desktop/revealin]
└─$ python3 ./revealin.py <handle>                                                    1 ⨯
[+] Handle : <handle>

[DEBUG] Cookie no more active, I re-login...
Email => <myemail>
Password => <mypassword>
[DEBUG] Cookies re-generated and valid !
Traceback (most recent call last):
  File "/home/osint/Desktop/revealin/./revealin.py", line 34, in <module>
    trio.run(main)
  File "/home/osint/.local/lib/python3.9/site-packages/trio/_core/_run.py", line 1932, in run
    raise runner.main_task_outcome.error
  File "/home/osint/Desktop/revealin/./revealin.py", line 24, in main
    target = await get_needed_info(as_client, handle)
  File "/home/osint/Desktop/revealin/lib/target.py", line 12, in get_needed_info
    req = await as_client.get(f"https://www.linkedin.com/voyager/api/identity/dash/profiles?q=memberIdentity&memberIdentity={handle}&decorationId=com.linkedin.voyager.dash.deco.identity.profile.FullProfile-64")
  File "/home/osint/.local/lib/python3.9/site-packages/httpx/_client.py", line 1305, in get
    return await self.request(
  File "/home/osint/.local/lib/python3.9/site-packages/httpx/_client.py", line 1147, in request
    response = await self.send(
  File "/home/osint/.local/lib/python3.9/site-packages/httpx/_client.py", line 1168, in send
    response = await self.send_handling_redirects(
  File "/home/osint/.local/lib/python3.9/site-packages/httpx/_client.py", line 1195, in send_handling_redirects
    response = await self.send_handling_auth(
  File "/home/osint/.local/lib/python3.9/site-packages/httpx/_client.py", line 1232, in send_handling_auth
    response = await self.send_single_request(request, timeout)
  File "/home/osint/.local/lib/python3.9/site-packages/httpx/_client.py", line 1269, in send_single_request
    timeout=timeout.as_dict(),
AttributeError: 'int' object has no attribute 'as_dict'
```

**Comment by ManuelBot59** [comment]
Replace "<handle>" with the target's email. 

ERROR ****************************
┌──(osint㉿osint)-[~/Desktop/revealin]
└─$ python3 ./revealin.py <handle>

CORRECT *************************
┌──(osint㉿osint)-[~/Desktop/revealin]
└─$ python3 ./revealin.py email@gmail.com

**Comment by capizarnik** [comment]
> Replace "" with the target's email.
> 
> ERROR **************************** ┌──(osint㉿osint)-[~/Desktop/revealin] └─$ python3 ./revealin.py
> 
> CORRECT ************************* ┌──(osint㉿osint)-[~/Desktop/revealin] └─$ python3 ./revealin.py [email@gmail.com](mailto:email@gmail.com)

does not work for me...
