### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by ManuelBot59** [mxrch/revealin#3]
┌──(root💀tedd)-[/home/tedd/TOOLS/revealin]
└─# python3 revealin.py https://www.linkedin.com/in/thert/               1 ⨯
[+] Handle : thert

Traceback (most recent call last):
  File "/home/tedd/TOOLS/revealin/revealin.py", line 34, in <module>
    trio.run(main)
  File "/usr/local/lib/python3.9/dist-packages/trio/_core/_run.py", line 1932, in run
    raise runner.main_task_outcome.error
  File "/home/tedd/TOOLS/revealin/revealin.py", line 22, in main
    as_client = await check_and_login()
  File "/home/tedd/TOOLS/revealin/lib/login.py", line 35, in check_and_login
    as_client = await check_session()
  File "/home/tedd/TOOLS/revealin/lib/login.py", line 23, in check_session
    cookies = json.loads(f.read())
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 15 (char 14)

**Comment by C3n7ral051nt4g3ncy** [comment]
@ManuelBot59 

1 - Uninstall 
2 - Make Virtual Environment (I used python3.9 -m venv virtual)
3 - Git clone the repo & cd revealin
4- `pip3 install -r requirements.txt`
5- Then launch `python3 revealin.py https://www.linkedin.com/in/thert/`
6- Use sockpuppet to input email and pw.
